# Generated by Django 5.2.7 on 2025-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='subdomain',
        ),
        migrations.RemoveField(
            model_name='hotelier',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
