# Generated by Django 5.2.7 on 2025-11-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_city_alter_hotel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
