# Generated by Django 5.2.7 on 2025-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_phone_number_alter_hotel_id_hotelier'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
