# Generated by Django 5.2.7 on 2025-11-09 23:11

import django.db.models.deletion
import hotels.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_profile',
            field=models.ImageField(blank=True, null=True, upload_to=hotels.models.upload_to),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(max_length=100)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('room_profile', models.ImageField(blank=True, upload_to=hotels.models.upload_to)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hotels.models.upload_to)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galery_images', to='hotels.room')),
            ],
        ),
    ]
