# Generated by Django 5.2.7 on 2025-11-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
    ]
