# Generated by Django 5.2.7 on 2025-11-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_remove_room_room_type_room_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
