# Generated by Django 5.2.7 on 2025-11-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='size_m2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
    ]
