# Generated by Django 5.2.7 on 2025-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_remove_hotel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
