# Generated by Django 5.2.7 on 2025-11-05 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_hotel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelier',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_tenant', to='hotels.hotel'),
        ),
    ]
