# Generated by Django 5.2.7 on 2025-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_hotelier_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_profile',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/profiles/<django.db.models.fields.CharField>/'),
        ),
    ]
