"""
Django settings for roomify project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oez$3ag$aq_=bb8^sw^^rpyv%=1nt7u=e3r8(kgd*+-ygt#(t@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = "accounts.CustomUser"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'roles',
    'rooms.apps.RoomsConfig',
    'customerpanel',
    'accounts.apps.AccountsConfig',
    'hotels.apps.HotelsConfig',
    'managerpanel'
    
]

SHARED_APPS = (
    'tenant_schemas',  # Obligatoire
    'tenants',         # L'app qui définit les modèles de tenants

    # Apps Django standard
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Votre app "public"
    'public',
)

TENANT_APPS = (
    # Apps Django (sauf admin, déjà dans shared)
    'django.contrib.contenttypes', # Requis par auth
    
    # Si vous décidez de mettre 'auth' par tenant (recommandé)
    'django.contrib.auth', 
    'django.contrib.sessions',
    'django.contrib.messages',

    # Votre app métier principale
    'hotels',

    # (Optionnel, mais recommandé) Une app 'users' pour votre AUTH_USER_MODEL
    # 'users', 
)

INSTALLED_APPS = []
INSTALLED_APPS += SHARED_APPS
INSTALLED_APPS += TENANT_APPS


MIDDLEWARE = [
    'tenant_schemas.middleware.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'customerpanel.middleware.CustomerMiddleware',
    'managerpanel.middleware.ManagerMiddleware',
    'tenancy.middleware.ActiveHotelMiddleware'
]

AUTHENTICATION_BACKENDS = [
    'accounts.backend.EmailBackend',   # ton backend personnalisé
    'django.contrib.auth.backends.ModelBackend',  # garde celui-ci pour compatibilité admin
]

ROOT_URLCONF = 'roomify.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'managerpanel.context_processors.get_recents_hotel_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'roomify.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'tenant_schemas.postgresql_backend',
        'NAME': "roomify",
        'USER':"postgres",
        "PASSWORD":"levelvertos",
        "HOST":'localhost',
        "PORT":"5432"
    }
}

DATABASE_ROUTERS = (
    'tenant_schemas.routers.TenantSyncRouter',
)

TENANT_MODEL = 'tenants.HotelTenant'
TENANT_DOMAIN_MODEL = 'tenants.Domain'
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static_files"]



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'




